name: CI/CD Pipeline - C#

on:
  push:
    branches: ["main"]

jobs:
  build-test-docker-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restaurar dependencias
        run: dotnet restore HelloWeb.sln

      - name: Compilar
        run: dotnet build --no-restore HelloWeb.sln

      - name: Ejecutar pruebas unitarias
        run: dotnet test --no-build HelloWeb.Tests/HelloWeb.Tests.csproj

      - name: Login en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir y subir imagen a Docker Hub
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hello-web:latest ./HelloWeb
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/hello-web:latest

      - name: Deploy en Render
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
